package com.crocworks.app.ui.theme

import androidx.compose.ui.graphics.Color

// Crocodile-inspired seed colors 🐊 — refreshed for M3 Express You
val CrocGreen = Color(0xFF1B8A4E)
val CrocTeal = Color(0xFF00897B)
val CrocDarkGreen = Color(0xFF145C34)

// Light theme — vibrant Express You palette
val md_theme_light_primary = Color(0xFF1B6D3A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F5B5)
val md_theme_light_onPrimaryContainer = Color(0xFF00210D)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD3E8D3)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1F12)
val md_theme_light_tertiary = Color(0xFF3A656E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEEAF5)
val md_theme_light_onTertiaryContainer = Color(0xFF001F26)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FFF6)
val md_theme_light_onBackground = Color(0xFF191C19)
val md_theme_light_surface = Color(0xFFF6FFF6)
val md_theme_light_onSurface = Color(0xFF191C19)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF404940)
val md_theme_light_outline = Color(0xFF707970)
val md_theme_light_outlineVariant = Color(0xFFBFC9BF)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EC)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF88D99B)
val md_theme_light_surfaceTint = Color(0xFF1B6D3A)
val md_theme_light_surfaceBright = Color(0xFFF6FFF6)
val md_theme_light_surfaceDim = Color(0xFFD6DBD4)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF0F5EE)
val md_theme_light_surfaceContainer = Color(0xFFEAEFE8)
val md_theme_light_surfaceContainerHigh = Color(0xFFE5EAE3)
val md_theme_light_surfaceContainerHighest = Color(0xFFDFE4DD)

// Dark theme — deep, rich Express You palette
val md_theme_dark_primary = Color(0xFF88D99B)
val md_theme_dark_onPrimary = Color(0xFF003919)
val md_theme_dark_primaryContainer = Color(0xFF005228)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F5B5)
val md_theme_dark_secondary = Color(0xFFB7CCB8)
val md_theme_dark_onSecondary = Color(0xFF233426)
val md_theme_dark_secondaryContainer = Color(0xFF394B3B)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3E8D3)
val md_theme_dark_tertiary = Color(0xFFA2CED9)
val md_theme_dark_onTertiary = Color(0xFF02363E)
val md_theme_dark_tertiaryContainer = Color(0xFF214D56)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEEAF5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF101510)
val md_theme_dark_onBackground = Color(0xFFDFE4DD)
val md_theme_dark_surface = Color(0xFF101510)
val md_theme_dark_onSurface = Color(0xFFDFE4DD)
val md_theme_dark_surfaceVariant = Color(0xFF404940)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9BF)
val md_theme_dark_outline = Color(0xFF8A938A)
val md_theme_dark_outlineVariant = Color(0xFF404940)
val md_theme_dark_inverseOnSurface = Color(0xFF101510)
val md_theme_dark_inverseSurface = Color(0xFFDFE4DD)
val md_theme_dark_inversePrimary = Color(0xFF1B6D3A)
val md_theme_dark_surfaceTint = Color(0xFF88D99B)
val md_theme_dark_surfaceBright = Color(0xFF353A35)
val md_theme_dark_surfaceDim = Color(0xFF101510)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0B100B)
val md_theme_dark_surfaceContainerLow = Color(0xFF181D18)
val md_theme_dark_surfaceContainer = Color(0xFF1C211C)
val md_theme_dark_surfaceContainerHigh = Color(0xFF262B26)
val md_theme_dark_surfaceContainerHighest = Color(0xFF313631)
